### ISSUE TITLE
Lib seems not to work

### ISSUE THREAD

**Issue by nxhoaf** [lukeweber/flac-as3-alchemy-wrapper#1]
Hi there, 

I want to record sound from mic, and then save it as .flac. Thanks to your flac-as3-alchemy, I can now do it. But due to some unknown errors, I can't do it. Here it what I did:
1. Create a new mic, set the rate to 16 as you said.
     mic.gain = 100;
            mic.rate = 16;
            mic.setSilenceLevel(0,4000);
2. After recording, I have a ouput ArrayBit, say bytes. I then used it as output of you lib. The encoding process succeed as the encodingCompleteHandler is invoked: 

private function encodeToFlac(bytes:ByteArray) : void { 
            var flacCodec:Object;
            flacCodec = (new cmodule.flac.CLibInit).init();

```
        var flacData : ByteArray = new ByteArray();
        flacData.endian = Endian.LITTLE_ENDIAN;
        flacCodec.encode(   encodingCompleteHandler, 
                            encodingProgressHandler, 
                            bytes, 
                            flacData, 
                            bytes.length, 
                            30);

        function encodingCompleteHandler(event:*):void {
            trace("FLACCodec.encodingCompleteHandler(event):", event);
            flacData.position = 0;
            //Alert.show(flacData.length.toString());

            (new FileReference()).save(flacData, ".flac");
```

//              encodedData.position = 0;
//              dispatchEvent( new FLACEvent(FLACEvent.ENCODING_COMPLETE, encodedData, getElapsedTime()) );
            }

```
        function encodingProgressHandler(progress:int):void {
            trace("FLACCodec.encodingProgressHandler(event):", progress);
```

//              dispatchEvent( new ProgressEvent(ProgressEvent.PROGRESS, false, false, progress, 100));
            }
        }

Can you tell me how must I do to make it works ?
Thank in advance!

**Comment by lukeweber** [comment]
I'm having trouble seeing the problem. Are you saying the output data is zero length?

**Comment by nxhoaf** [comment]
In fact, the length is not-null, that is, the .flac has data inside, but 
when I tried to open it, I received this error (in attached file).

I will create a simple project and send it to you.

Thank.

**Comment by lukeweber** [comment]
So, this I believe is native flac, http://flac.sourceforge.net/faq.html (What is the difference between (native) FLAC and Ogg FLAC?), otherwise maybe the header isn't being written perfectly.

Does the output file start with?
"fLaC", the FLAC stream marker in ASCII, meaning byte 0 of the stream is 0x66, followed by 0x4C 0x61 0x43

As well, you might try to import the flac file into audacity and see if the audio is fine there. Then it would suggest that the missing link might just be the ogg container that you're expecting for whatever audio program you're hoping for which could be solved by changing in the c code FLAC__stream_encoder_init_stream to  FLAC__stream_encoder_init_ogg_stream, then you would have flac inside ogg.

I know the underlying flac data is correct because I tested my own a long time ago by firing it off to the google speech api.

**Comment by nxhoaf** [comment]
Sorry for the late response, here is my source code, can you use it to 
test what I do ?

<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
                        xmlns:s="library://ns.adobe.com/flex/spark"
                        xmlns:mx="library://ns.adobe.com/flex/mx"
                        width="301" height="410"
                        title="Simple Recorder">
fx:Declarations



/fx:Declarations
<fx:Script >

<![CDATA[

```
         import cmodule.flac.CLibInit;

         import mx.controls.Alert;
         var mic:Microphone = Microphone.getMicrophone();
         var bytes:ByteArray;
         var flacData:ByteArray;
         public function recordIsClicked() :void {
             this.bytes = new ByteArray;
             mic.gain = 100;
             mic.rate = 16;
             mic.setSilenceLevel(0,4000);

             // Remove playback listener if any
             mic.removeEventListener(SampleDataEvent.SAMPLE_DATA, 
```

onPlaying);
                 // Add record listener
                 mic.addEventListener(SampleDataEvent.SAMPLE_DATA, 
onRecording);
                 label.text = "Recording...";
                 record.enabled = false;
                 toFlac.enabled = false;
                 stop.enabled = true;
             }

```
         public function stopIsClicked() {
```

mic.removeEventListener(SampleDataEvent.SAMPLE_DATA,onRecording);
                 bytes.position = 0;
                 label.text = "Click Record to begin.";
                 record.enabled = true;
                 toFlac.enabled = true;
                 stop.enabled = false;
                 if (bytes.length > 0) {
                     bytes.position = 0;
                     var sound:Sound = new Sound();

sound.addEventListener(SampleDataEvent.SAMPLE_DATA,playback);
                     sound.play();
                 }
             }

```
         private function onPlaying(event:SampleDataEvent): void {
             var sample:Number;
             for (var i:int = 0; i < 8192; i++) {
                 if (!bytes.bytesAvailable) return;
                 sample = bytes.readFloat();
                 event.data.writeFloat(sample);
                 event.data.writeFloat(sample);
             }
         }

         private function onRecording(event:SampleDataEvent):void {
             while (event.data.bytesAvailable) {
                 var sample:Number = event.data.readFloat();
                 bytes.writeFloat(sample);
             }
         }

         public function toFlacIsClicked() : void {
             var flacCodec:Object;
             flacCodec = (new cmodule.flac.CLibInit).init();
             bytes.position = 0;
             flacData = new ByteArray();
             flacData.endian = Endian.LITTLE_ENDIAN;
             flacCodec.encode(encodingCompleteHandler, 
```

encodingProgressHandler, bytes, flacData, bytes.length, 10);

```
         }

         function encodingCompleteHandler(event:*):void {
             flacData.position = 0;
             Alert.show(flacData.toString());
             (new FileReference()).save(flacData, ".flac");
         }

         function encodingProgressHandler(progress:int):void {
         }

         function playback(event:SampleDataEvent): void {
             var sample:Number;
             for (var i:int = 0; i < 8192; i++) {
                 if (!bytes.bytesAvailable) return;
                 sample = bytes.readFloat();
                 event.data.writeFloat(sample);
                 event.data.writeFloat(sample);
             }
         }
         function recording(event:SampleDataEvent):void {
             while (event.data.bytesAvailable) {
                 var sample:Number = event.data.readFloat();
                 bytes.writeFloat(sample);
             }
         }
     ]]>
```

/fx:Script
<s:Group x="24" y="24" width="250" height="212">
<s:Label id="label" x="10" y="80" width="240" height="55" fontSize="24" 
text="Click Record to begin."/>
/s:Group
<s:Group x="24" y="262" width="250" height="134">
<s:Button id="record" name="record" x="40" y="31" label="Record" 
click="recordIsClicked();"/>
<s:Button id="stop" name="stop" x="150" y="30" label="Stop" 
enabled="false" click="stopIsClicked();"/>
<s:Button x="90" y="78" id="toFlac" name="toFlac" label="To Flac" 
enabled="false" click="toFlacIsClicked();"/>

/s:Group
/s:WindowedApplication

Also, I'm now working with google speech api, I succeeded in sending 
.flac to google api and receiving the output text. As the next step, I 
want to record audio from micro, encode it as .flac and then send it to 
google. Regarding header, The first four bytes is ff f8 35 08 ( I used 
the link below to view the .flac file)
http://www.fileformat.info/tool/hexdump.htm

I have a small Flash Builder project, If you use flash builder too, can 
I send it to you to clarify the problem ?

By the way, what did you do to make a .flac file and send it to google, 
can you send it to me ? Because it's exactly what I want to do now.

Thank in advance.

**Comment by lukeweber** [comment]
Okay, so you'll need to convert your 32 bit floats to 16 bit shorts for this to work. As well you won't be able to access the api directly through the web unfortunately due to crossdomain permissions on google's side. You could circumvent this with a simple proxy if you wanted, although not condoning as they might very easily just block your ip that's making a disproportionate number of requests.

This is a quick and dirty function that would do the conversion more or less:

``` actionscript
private static const FLOAT_MAX_VALUE:Number = 1.0;
private static const SHORT_MAX_VALUE:int = 0x7fff;

/**
* Converts an (raw) audio stream from 32-bit (signed, floating point) 
* to 16-bit (signed integer).
* 
* @param source The audio stream to convert.
*/
 public function convert32to16(source:ByteArray):ByteArray {
        trace("BitrateConvertor.convert32to16(source)", source.length);

            var result:ByteArray = new ByteArray();
            result.endian = Endian.LITTLE_ENDIAN;

            while( source.bytesAvailable ) {
                var sample:Number = source.readFloat() * SHORT_MAX_VALUE;

                // Make sure we don't overflow.
                if (sample < -SHORT_MAX_VALUE) sample = -SHORT_MAX_VALUE;
                else if (sample > SHORT_MAX_VALUE) sample = SHORT_MAX_VALUE;

                result.writeShort(sample);
            }

            trace(" - result.length:", result.length);
            result.position = 0;
            return result;
        }
```

Anyways here is the link with some example code for messing around with the speech api. http://mikepultz.com/2011/03/accessing-google-speech-api-chrome-11/. I was trying to play the headerless flac audio in sox and wasn't having a lot of luck myself. The output audio though will work on the google api from my own test. I don't have the client code for google's api handy at the moment, but it's really just a request with the output of the encoder. 

Luke

**Comment by nxhoaf** [comment]
It still not work. I've just used your function to convert my _bytes_ to 
_rawData_ using convert32to16
public function toFlacIsClicked() : void {
                 var flacCodec:Object;
                 flacCodec = (new cmodule.flac.CLibInit).init();
                 bytes.position = 0;
                 var rawData: ByteArray = new ByteArray();
                 flacData = new ByteArray();
                 rawData = convert32to16(bytes);
                 flacData.endian = Endian.LITTLE_ENDIAN;
                 flacCodec.encode(encodingCompleteHandler, 
encodingProgressHandler, rawData, flacData, rawData.length, 10);
             }

```
         /**
          * Converts an (raw) audio stream from 32-bit (signed, 
```

floating point)
              \* to 16-bit (signed integer).
              *
              \* @param source The audio stream to convert.
              */
             public function convert32to16(source:ByteArray):ByteArray {
                 trace("BitrateConvertor.convert32to16(source)", 
source.length);

```
             var result:ByteArray = new ByteArray();
             result.endian = Endian.LITTLE_ENDIAN;

             while( source.bytesAvailable ) {
                 var sample:Number = source.readFloat() * 
```

SHORT_MAX_VALUE;

```
                 // Make sure we don't overflow.
                 if (sample < -SHORT_MAX_VALUE) sample = 
```

-SHORT_MAX_VALUE;
                     else if (sample > SHORT_MAX_VALUE) sample = 
SHORT_MAX_VALUE;

```
                 result.writeShort(sample);
             }
             trace(" - result.length:", result.length);
             result.position = 0;
             return result;
         }
```

Regarding the full source code, you can find out in attached file. Can 
you please tell me did something go wrong ?

**Comment by nxhoaf** [comment]
```
Ok, thank you  anyway
```

**Comment by lukeweber** [comment]
Sorry, that was my mistake, anyways forgetting playback for a second.

What happens if you save the new file you have and post it with wget:

wget --post-file=test_web.flac --header="Content-Type: audio/x-flac; rate=16000" -O result.txt "https://www.google.com/speech-api/v1/recognize?xjerr=1&client=chromium&lang=en-US"

What's in result.txt

**Comment by nxhoaf** [comment]
It's the good one, it means that the conversion works, but, for 
curiosity, why doesn't it work when I double-click on the file ?

**Comment by nxhoaf** [comment]
Sorry, I forgot attached files :)

**Comment by lukeweber** [comment]
As I said, it's headerless raw flac audio. Basically the programs don't know what type of audio they're getting, so they don't know how to play it back. 

Anyhow, audio works, if you wanted flac with headers inside an ogg container so it was playable inside most apps, then you would take the changesets that I reverted to use ogg_stream and then you also need to compile in ogg into this project, which would require getting the source and then a diff on the Makefile file a bit like this or some variation on it. I think the example flac decoder from adobe includes ogg so you could use that as a reference as well:

``` diff
diff --git a/lib/Makefile b/lib/Makefile
index 5ae6dd6..6d6d8d5 100644
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -6,9 +6,10 @@ CINCLUDE = \
        -I$(LIB_FLAC_PATH)include/ \
        -I$(LIB_FLAC_PATH) \
        -I./flac121/include/ 
+       //ogg header includes here

 CC_SWITCHES = -Wall -O3 $(CINCLUDE)
-DEFS= -DHAVE_CONFIG_H
+DEFS= -DHAVE_CONFIG_H -DFLAC__HAS_OGG

 PNAME = flac

@@ -30,17 +31,25 @@ SOURCES=\
        stream_encoder.c \
        stream_encoder_framing.c \
        window.c
+       //add extra ogg files here as part of flac
+ //flac121/libFLAC/ogg_helper.c
+ //flac121/libFLAC/ogg_encoder_aspect.c    flac121/libFLAC/ogg_mapping.c
+
+//compile an ogg lib here
+OGG_SOURCES= \
+       //specific ogg source files here

 RES_SOURCES=$(addprefix $(LIB_FLAC_PATH), $(SOURCES))
 MAIN = flac_as3_encoder.c

 MAIN_OBJ = $(MAIN:.c=.o)
+OGG_OBJ = $(OGG:.c=.o)
 OBJ = $(RES_SOURCES:.c=.o)

 all: compile_swc clean

-compile_swc: $(OBJ) $(MAIN_OBJ)
-       $(CC) $(CFLAGS) -swc -o $(PNAME).swc $(OBJ) $(MAIN_OBJ)
+compile_swc: $(OGG_OBJ) $(OBJ) $(MAIN_OBJ)
+       $(CC) $(CFLAGS) -swc -o $(PNAME).swc $(OGG_OBJ) $(OBJ) $(MAIN_OBJ) 
        mv $(PNAME).swc ../bin/.
```

**Comment by nxhoaf** [comment]
But it doesn't matter, As I said, I don't need to open the .flac myself, 
but it's action script which will send it to google and get the result.

Thank you for you help, many thank!!!

**Comment by lukeweber** [comment]
Good luck, don't forget that you won't be able to connect to google directly through actionscript outside of your local debug versions unless they release this as an official api.
